site: Board
title: Board de oportunidadesilimitadas.com
greetings: Hola 👋👋
description: >-
  Board de vista detallada de webs y apps de Inteligencia Artificial
lang: es
image: https://res.cloudinary.com/notee/image/upload/v1640411291/notes/imgseo.jpg
timezone: America/Bogota
repo: https://github.com/lucfreelance/board-board
data-theme: light # default theme "dark" | "light"
discus-identifier: lucfreelance
default-thumb: https://i.imgur.com/7JpjvXQ.png

author:
  name: oi-ia
  url: https://oportunidadesilimitadas.com
  bio: Oportunidades ilimitadas en Inteligencia Artificial en Español.
  avatar: https://i.imgur.com/7JpjvXQ.png
  username: admin
  github: https://github.com/lucfreelance/
  twitter: o_ilimitadas
  email: ilimitadasoportunidades@gmail.com

twitter:
  username: o_ilimitadas
  card: summary_large_image

# Font Settings
googlewebfonts: family=Archivo:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://lucfreelance.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/board" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug/
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: https://res.cloudinary.com/notee/image/upload/v1640411291/notes/imgseo.jpg
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

relative_links:
  enabled: true
  collections: false
